project: 
  render: 
    - ".qmd"
    - "!devel"
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Anders Nybakk"
  date: "2024-11-22"
  chapters:
    - index.qmd
    - 03-stat-inf.qmd
    - kilder.qmd

bibliography:
    - resources/references.bib
    - resources/ref2.bib

csl: resources/citation-style.csl 

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



