project: 
  render: 
    - ".qmd"
    - "!devel"
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Kandidatnummer: 503"
  date: "2024-11-22"
  chapters:
    - index.qmd
    - Oppgave-1.qmd
    - Oppgave-2.qmd
    - Oppgave-3.qmd
    - Oppgave-4.qmd
    - Oppgave-5.qmd
    - Labrapport.qmd
    - Filosofihistore.qmd
    - kilder.qmd

bibliography:
    - resources/ref1.bib
    - resources/ref2.bib
    - resources/ref3.bib
    - resources/ref4.bib
    - resources/ref5.bib
    - resources/ref6.bib
    - resources/ref7.bib

csl: resources/citation-style.csl 

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



