---
title: "Filosofihistore"
author: "Kandidatnymmer: 503"
bibliography: resources/ref7.bib
---

## Oppgave 1


*Ifølge Hume er det umulig å rasjonelt begrunne bruken av induksjon. Hva er argumentet for denne konklusjonen? Gi en innvending mot ett av premissene i Humes argument og prøv å svare på denne innvendingen på Humes vegne.*


Induksjon handler om å predikere et resultat ut fra tidligere erfaringer – «fremtiden vil være som fortiden». Ta en pakke med seks egg for eksempel. Kan vi gå ut fra at om de første fem eggene i pakken var gode, så må det sjette også være bra?  Den skotske filosofen David Hume kallte dette for uniformitetsprinsippet og var svært kritisk til denne måten å tenke på. Han mente at uniformitetsprinsippet ikke kunne bevises på en rasjonell måte fordi naturen ikke trenger å være uniform [@okasha2016, s. 20-22]. Hvis vi tar utgangspunkt i eksempelet med egg kan vi forklare dette på en enklere måte. Hvis en person bruker induksjon til å anta at det sjette egget er bra fordi de andre eggene var bra vil dette være det eneste argumentet han/hun kan komme med. Hvis personene har rett og du igjen spør hvorfor egget var bra, vil personen igjen komme tilbake til begrunnelsen om at de andre eggene var bra. Altså: *A* vil skje fordi *B* har skjedd, og hvorfor *A*? fordi *B*. Hume mente at dette var et sirkulært argument hvor man aldri kan finne noen tilfredsstillende forklaring på [@okasha2016, s. 22].

Dette argumentet tar også utgangspunkt i at naturen er uniform - altså uniformitetsprinsippet som jeg nevnte tidligere. Hume mente at uniformitetsprinsippet ikke kunne bevises. Grunnen til dette er at vi ganske lett kan forestille oss at naturen ikke er uniform. Uforutsette ting kan skje. Egget vi har brukt som eksempel kan være eldre enn de andre i pakken, det kan ha fått en skade, eller komme fra en syk høne, og kan derfor være dårlig selv om de første fem var bra. Hume argumenterer derfor med at selv om naturen har vært uniform fram til nå, kan vi ikke konkludere med at den vil fortsette å være uniform [@okasha2016, s. 22].

Hume mener altså at en uniform verden ikke kan bevises, og kun kan forklares med sirkulære argument. Hume mente derfor at vi ikke med sikkerhet kan predikere framtid eller et utfall basert på tidligere erfaringer, obserfasjoner eller sannsynlighet fordi fortiden ikke er et sikkert grunnlag for en slik påstand. Humes påstand om at man ikke kan rasjonelt forsvare induksjon uten å bruke et sirkulært argument er det som i dag kalles "Induksjonsproblemet" [@okasha2016, s. 22].

Mange filosofer og forskere har forsøkt å løse dette problemet. Et eksempel kan være å vise til hvor langt man har kommet innenfor vitenskapen ved å bruke induksjon. Ved hjelp av induksjon har vi landet på månen, oppfunnet laseren og så videre. Personer som ikke har stolt på induksjon kan i verste fall ha dødd på grusomme måter fordi de har spist gift eller hoppet fra bygninger i tro om at de kan fly [@okasha2016 s. 21-22]. Et slik argument ville nok ikke overbevise Hume om at induksjonsproblemet ikke var reelt. Han ville nok kontre med at dette argumentet kun var gyldig hvis man antok at uniformitetsprinsippet stemte – noe han mente det ikke alltid gjorde. Han innrømmet på en annen side at induksjon ble brukt hele tiden, både i hverdag og vitenskap, men det vil ikke bety at det er rasjonelt. Poenget til Hume var nemlig at man ikke kan med sikkerhet predikere hva som kommer til å skje basert på det som har skjedd tidligere. I dag kan vi argumentere med at en antakelse om hva som kommer til å skje basert på statistisk analyse vil være troverdig, men også dette ville han kalt irrasjonelt fordi det baserer seg på uniformitetsantakelser [@okasha2016,s 20-22].

Okasha viser også til et annet forsøk på å løse induksjonsproblemet kom fra filosofen Peter Strawson. Strawson mente at det ikke gav mening å stille spørsmål ved validiteten til induksjon. Han mente at induksjon er et hjelpemiddel for å avgjøre om antakelsene våre har validitet, og at det da gir lite mening å spørre om induksjon i seg selv er valid. Han sammenlikner dette med å stille spørsmålet om en lov i et lovverk er lovlig. Loven er til for å si hva som er lovlig og ikke, og at det da ikke gir mening å lure på om standarden i seg selv er lovlig. Strawson mener at det samme gjelder for induksjon, men det er svært delte meninger om han har klart å motbevise induksjonsproblemet [@okasha2016, s. 22-23].


## Oppgave 2

*Gi en kort beskrivelse av falsifikasjonisme og si litt om hvorfor Popper var motivert til å utvikle denne teorien. Presenter så ett problem med teorien og vurder hvorvidt problemet kan løses.*

Karl Popper var enig med Humes filosofi om at induksjon var irrasjonelt og at man ikke kan predikere framtid basert på fortid. Han mente også at Humes induksjonsproblem var umulig å løse, og at induksjon rett og slett var et mislykket prosjekt som ikke burde ha noe med vitenskap å gjøre. Som et svar mot induksjon kom Popper med en deduktiv metode som kalles «*Falsifikasjonisme*». Kort forklart er dette en teori som sier at vi aldri kan bevise em hypotese – bare motbevise den, altså falsifisere. Popper mente at alle vitenskapelige hypoteser må være falsifiserbare. Dette vil ikke si at alle vitenskapelige teorier skal være feil, men at det skal være mulig å forsøke og motbevise de gjennom testing [@okasha2016].

Popper mente at flere såkalte vitenskapelige teorier ikke var tilstrekkelig falsifiserbare til å kvalifiseres som vitenskap, men i stedet var pseudo-vitenskap. Freuds psykoanalyse var en av teoriene Popper ikke anerkjente som ekte vitenskap. Grunnen til dette var at uansett hva en pasient gjorde eller led av kunne Freud forklare det med teorien sin. Det var aldri noe som ikke passet inn i teorien og den ville aldri bli motbevist. Ettersom den aldri kunne motbevises var den ikke kvalifisert til å bli kalt vitenskap ifølge Popper [@okasha2016, s. 12-13]. Et eksempel Popper selv bruker er at en mann dytter et barn ut i vannet for å drukne det, og at en man hopper ut i vannet for å redde barnet. Dette er motstridende handlinger som begge passer like godt i teoriene til Freud og Adler, uten at teoriene motbevises. Dette mente Popper var et bevis for svakhetene til teoriene deres, ikke styrkene [@popper1969].

Denne type teorier som aldri kunne motbevises, men alltid fant bekreftende bevis var grunnen til at Popper kom med teorien om falsifikasjonisme. Han mente som sagt at en hypotese bare var vitenskapelig hvis den kunne falsifiseres. En vitenskapelig hypotese skulle predikere noe – gjerne så nøyaktig som mulig, og den skulle være mulig å teste og eventuelt motbevises. Hvis et forsøk ikke klarte å motbevise hypotesen var den ikke bekreftet, bare styrket. Eksempelet Popper mente at all vitenskap burde strebe etter var Einsteins generelle relativitetsteori. Her kom Einstein med en presis prediksjon om at solens gravitasjon ville påvirke stråling fra stjerner. Dette ble senere testet under en solformørkelse og observasjonene stemte med Einstein prediksjon. Dette var akkurat det Popper mente var korrekt vitenskap – en presis detaljert prediksjon som kunne testes [@popper1969].

En utfordring med Poppers teori om falsifikasjonisme er at den vil utelukke, eller i alle fall gjøre det vanskelig for noen fagfelt å passe inn i hans definisjon av vitenskap. I naturvitenskapelige fagfelt som fysikk er det relativt enkelt å lage tester som skal forsøke å falsifisere en hypotese. I psykologi for eksempel kan dette være langt vanskeligere fordi det kan handle om hypoteser som ikke er målbare. Et eksempel kan være følgende to påstander.

1.  Et barn vokser opp med en kriminell far. Barnet ser opp til faren sin og ønsker å bli som han. Barnet vil ende opp som kriminell selv.

2.  Et barn vokser opp med en kriminell far. Barnet er flau over faren sin og han handlinger og ønsker å ta avstand fra det. Barnet vil ende opp som politi.

Begge disse hypotesene er plausible, men det vil være umulig å lage en test som motbeviser eller beviser de. Psykologi, personlighet, samfunn og andre personer er variabler som er umulig å fjerne og som vil hindre et eventuelt forsøk i å være reliabelt. Her kan vi bare vente å se på oppveksten til barnet og så trekke en konklusjon etterpå slik som Freud og Adler gjorde i sin tid. Dette vil ikke være særlig imponerende eller vitenskapelig ifølge Popper, men det betyr ikke at påstandene er feil.

En mulig løsning på dette problemet er å kombinere deduksjon med induksjon ved hjelp av statistikk og sannsynlighetsregning. I stedet for å si med sikkerhet at 1: barnet vil bli kriminelt, eller 2: barnet vil bli politi, kan man se på statistikk for barn som har vokst opp under liknende forhold, og regne ut sannsynlighetene for hva som vil skje med dette barnet. For eksempel 1: ut fra barnets oppvekst vil det være x % sannsynlig at barnet selv vil bli kriminelt, eller 2: ut fra barnets oppvekst vil det være x % sannsynlig at barnet vil ta avstand fra det livet og bli politi. Det kan altså være mulig å kombinere deduksjon og induksjon.
