# Forord {.unnumbered}

Dette er mappeeksamen for kandidatnummer 503 i IDR4000 - Kvantitativ metode og statistikk høsten 2024. Gjennom dette studiet har vi som studenter lært om kvantitativ forskningsmetodikk i alle stadier i planlegging og gjennomføring av forskningsprosjekt på mennesker. Det har blitt gjennomført med praktisk innsamling og analyse av data knyttet til fysiologiske variabler, cellebiologiske variabler og molekylærbiologiske variabler, med særlig fokus på de to sistnevnte. Statistiske metoder som er relevant for fagområdet har blitt gjennomgått i teori og praksis og lært om filosifihistorie. Vi har i løpet av studiet hatt praktiske øvelser, tester og forsøk på fysiologi- og molekylærlab, samlet inn data og skrevet rapporter. Vi har gjennomført simulerte forsøk i R, og utført statistiske analyser og beregninger ut fra simuleringen. Vi har analysert og vurdert forskningsartikler, og skrevet vår egen artikkel ut fra tidligere datainnsamlinger. Disse forskjellige undervisningsmetodene har vært etterfulgt av innlevering av rapporter og arbeidskrav.

Denne mappeeksamenen er resultatet av dette arbeidet. Den består av totalt sju arbeidskrav som har blitt vurdert og etter videre arbeid med disse leveres de nå som en samlet mappeeksamen. Et av målene med dette emnet er å lære hvordan man kan lage reproduserbare rapporter. Arbeidet med mappeeksamen har derfor blitt gjort i R, og lagret som repository på github. For å se nærmere på arbeidet inkludert koder som har blitt brukt legger jeg med lenke til min repository: https://github.com/Nybakk/mappeeksamen-idr4000-anders-nybakk 