---
title: "Studiedesign"
author: "Kandidatnummer: 503"
format: html
code-fold: true
execute:
  warning: false  # Skjuler varselmeldinger
editor_options: 
  chunk_output_type: console
bibliography: resources/ref4.bib
---

## Indroduksjon

I denne oppgaven skal jeg analysere og sammenlikne fem forskningsartikkler som undersøker samme tema. Tema jeg har valg er *"Blokkperiodisering og VO*<sub>2max</sub>". Jeg skal forsøke å bruke QALMRI-metoden for å analysere og sammenlikne artiklene på en systematisk og god måte. QALMRI står for "Questions", "Alternatives", "Logic", "Method", "Results", "Inferences", og handler om å systematisk analysere hva forfatterne ønsker å finne ut av, hva de torr vil skje, logikken bak hypotesen, metodene de har brukt i forskningen, resultatene og hva de betyr [@brosowsky2020].

Artiklene jeg har valgt er:

-   *"Block training periodization in alpine skiing: eVects of 11-day HIT on VO*<sub>2max</sub> and performance" - [@breil2010]
-   *"Block periodization of high-intensity aerobic intervals provides superior training effects in trained cyclists"* - [@rønnestad2012]
-   *"Effects of 12 weeks of block periodization on performance and performance indices in well-trained cyclists"* - [@rønnestad2012a]
-   *"Training Prescription Guided by Heart Rate Variability Vs. Block Periodization in Well-Trained Cyclists"* - [@javaloyes2020]
-   *"No Differences Between 12 Weeks of Block- vs. Traditional-Periodized Training in Performance Adaptations in Trained Cyclists"* - [@almquist2022]

Det skal sies at ikke alle artiklene jeg har valgt i denne oppgaven ser spesifikt på sammenhengen mellom bolkperiodisering og VO<sub>2max</sub>. De fleste av studiene ser på den generelle effekten bolkperiodisering har på prestasjonsevnen til utøverne. Ettersom VO<sub>2max</sub> er svært viktig for utholdenhetsidretter har jeg likevel valgt å fokusere på dette. Tester som går på andre egenskaper kommer jeg derfor ikke til å fokusere så mye på her.

## Hoveddel

### Grunnlag for studiene

Hovedfokuset til studiene jeg har valgt er å se på effekten av blokkperiodisert trening, med fokus på utholdenhet. Fire av artiklene ser spesifikt på hvordan effekten er for syklister, mens den siste tar for seg alpinister. [@rønnestad2012], [@rønnestad2012a] og [@almquist2022] sammenlikner i sine artikler effekten av blokkbasert trening (BP) med tradisjonell periodisering (TP). [@javaloyes2020] sammenlikner effekten av BP med *"heart rate variability guided training"* (HRV). [@breil2010] som forskjer på alpinister skiller seg også ut fra dette fordi de sammenlikner ikke BP med en annen form for periodisering. De forskjer utelukkende på hva en blokk med høyintensitetsintervaller (HIT) gjør med den aerobe kapasiteten til junior-alpinister.

[@breil2010], [@rønnestad2012], [@rønnestad2012a] har alle en hypotese om at BP vil gi en større forbedring i aerob kapasitet enn TP. Dette gi mening fordi det blir referert til studiene i artiklene. [@breil2010] sine funn blir referet til i [@rønnestad2012], og [@rønnestad2012a] referer igjen til sitt eget studie tidligere det samme året, og handler mye om å utvide forskningen de selv har gjort. Tanken bak BP er å lure kroppen til og styrkes raskere som følge av en relativt rask belastningsøkning i form av en høyintensitets treningsbolk på for eksempel en uke. Det er da viktig at man eterfølger dette med en rolig bolk slik at kroppen får tid til å restituere seg. Tanken er at en slik periodisering skal gi en raskere fremgang en TP hvor man fordeler de harde øktene jevnt utover treningsperioden.

[@almquist2022] presenterer ingen klar hypotese, men viser til nyere forskning hvor resultatene viser at BP ikke gir noe særlig bedre resultat enn andre former for periodisering som TP. Motivasjonen bak denne forskningen og artikkelen virker å være å undersøke hva som faktsik stemmer av tidligere forskning - altså om BP er bedre enn TP, eller ikke.

[@javaloyes2020] har ingen klar hypotese i sin artikkel men viser til annen forskning som viser at HRV kan gi en mer pålitelig formening om en utøvers evne til å trene. Ut fra utøverens HRV-score før trening kan man bestemme hva slags intensitet treningsøkten skal ha. Høy HRV-score = høy intensitet og motsatt.Dette kan altså være en måte å få optimalisert treningen for hver utøver individuelt ut fra dagsfor slik at treningen også blir optimal [@walker2024]. Det blir ikke skrevet eksplisitt, men det virker som om de har en hypotese om at HRV kan være en bedre måte å periodisere treningen etter enn BP.

### Sudiedesign og forskningsmetoder

Alle studiene har som mål å finne ut om en form for periodisering er mer effektiv enn en annen. I de fleste studiene jeg har valgt er det BP som undersøkes med en kontrollgruppe som har TP, men unntak av studien til [@javaloyes2020] som sammenlikner HRV med BP. Dette kan likne på det [@hulley2013] kaller *"Case Controll Studies"*, men passer samtidig ikke helt fordi det beskrives som en forskningsmetode som brukes for å finne ut hvordan en bestemt diagnose påvirker en gruppe, men "diagnosen" kan kanskje byttes ut med treningsmetode.

Studiene kan også minne om *"Randomized blinded trial"* som brukes for å finne ut om en behandling faktisk virker. Disse studiene blir blindet som vil si at deltakerne ikke vet om de er med i intervensjonsgruppen eller kontrollgruppen - derfor passer dette heller ikke helt. Alt i alt er det nok designformen *"Randomiserte kontrollerte studier"* som passer best hvor man deler utvalget tilfeldig, slik at eventuelle ulikheter i gruppene også blir tilfeldig. Alle studiene deler i hvert fall utvalget i to grupper: intervensjonsgruppe (BP eller HRV i [@javaloyes2020] sitt stude) og en kontrollgruppe (TP eller BP i [@javaloyes2020] sitt studie).

Alle studiene har utvalg med godt trente utøvere. I studien til [@breil2010] består utvalget av eliteutævere på juniornivå. I de fire sykkelstudiene er utøverne alle godt trente syklister som enten konkurrerer aktivt eller som har bakgrunn fra konkurransesykling. Ut ifra tallene som blir presentert for VO<sub>2max</sub> er de fleste utøverne i studiene er på prestasjonsnivå 3 etter modellen til [@pauw2013], og noen på nivå 2 (men dette er hovedsaklig alpinister hvor VO<sub>2max</sub> ikke er like viktig som for syklister). Noen utøvere er også på nivå 4 og 5 i følge [@almquist2022].

I studiene til [@rønnestad2012] og [@rønnestad2012a] meldte deltakerne seg frivillig for å delta på prosjektet, men alle var som sagt godt trente eller aktive syklister. [@breil2010] hentet deltakerne fra et nasjonalt treningssenter og [@almquist2022] fra en lokal sykkelklubb. [@javaloyes2020] skriver ikke hvor de hentet sine deltakere fra, men at de ble plukket ut på bakgrunn av kvalifikasjoner. Ingen av studiene oppgir noen utregning for statistisk styrke, ut fra utvalgene kan man anta at det ikke er meningen at de skal være repressentative for hele populasjonen. Forskningen i disse artiklene handler nok hovedsaklig om prestasjonsutvikling for aktive utøvere.

Alle studiene har forsøkt å standardisere så mye som mulig. Utøverne har fått instrukser i forkant av pretest om å unngå harde økter rett før testen, hva de kan spise og drikke på testdagen og liknende. I alle prosjektene blir det også gjort flere tester som VO<sub>2max</sub>, sprint, laktatprofil, spenst og så videre, og i noen av prosjektene foregår testene over to dager. I alle prosjektene er derfor rekkefølgen på testingen også standardisert. Treningsopplegget mellom testene er selvfølgelig laget og standardisert av prosjektlederne ettersom det er effekten av disse de skal undersøke. Varigheten på treningsperiodene varierer en del. I studiene til [@breil2010] og [@rønnestad2012] trener utøverne i 4 uker mellom testene, og i gruppen med BP har de først en hard uke med mye HIT etterfulgt av tre rolige uker med færre HIT-økter, mens TP hadde jevn treningsbelastning hele perioden. [@rønnestad2012a] og [@almquist2022] la opp treningen likt, men over 12 uker i stedet for fire og da med tre treningsblokker i BP-gruppen. [@javaloyes2020] hadde et treningsopplegg som gikk over åtte uker hvor HRV-gruppen trente ut fra HRV-scoren de fikk hver morgen, og BP-gruppen fulgte et forhåndsbestemt blokk-opplegg.

Det har blitt brukt veldig like former for statistisk analyse i studiene. Utregning av standard avvik blir gjort i alle studiene og blir oppgitt som en del av resultatene. De fleste studiene med unntak av [@almquist2022] understreker at det blir gjort en ANOVA-analyse for å sammenlikne gruppene. T-test blir gjennomført av [@breil2010], [@rønnestad2012] og [@rønnestad2012a], mens [@almquist2022] og [@javaloyes2020] bruker *"Shapiro-Wilks-test"*. Sistnevnte bruker også en *"Levene's-test"*. Alle studeiene regner en p-verdi \< 0,05 som statistisk signifikant.

### Resultat og konklusjon

I samtlige studier var BP den formen for periodisering som gav mest framgang på VO<sub>2max</sub>. Spesielt i studiene til [@breil2010], [@rønnestad2012] og [@rønnestad2012a] kommer BP godt ut, og har signifikan resultat - noe TD ikke har. I studien til [@almquist2022] er forskjellen vesentlig mindre. Her har BP fortsatt en fordel fremfor TP, men mmye mindre enn resultatene fra de andre studiene sier. En mulig forklaring på dette i følge forfatterne kan være den store spredningen i prestasjonsnivå. I denne studien varierer deltakerne fra nivå 2-5 [@pauw2013], så individuell framgang som følge av økning i treningsbelastining kan skjule eventuelle forskjeller mellom BP og TP. BP har også bedre effekt på VO<sub>2max</sub>. enn HRV i følge resultatene i studien til [@javaloyes2020], men også her er forskjellene mindre enn de tre første studiene.

Studiene til [@breil2010], [@rønnestad2012] og [@rønnestad2012a] konkluderer med at BP *kan* være fordelaktig for å forbedre aerob kapasitet. Spesielt [@breil2010] er positive til BP, men dette er også en av de korteste studiene, og også den studien som tydeligst hadde fokus på VO<sub>2max</sub>. Selv om de er positive til BP stiller de fortsatt et spørsmålstegn til hvor viktig VO<sub>2max</sub> er for alpinister - selv om tidligere studier viser at alpinister har høyere VO<sub>2max</sub> enn gjennomsnittet i populasjonen. [@rønnestad2012] og [@rønnestad2012a] viser som sagt også til at disse studiene tyder på at BP kan være fordelaktig i forhold til TP, men er tydelige på at det er vanskelig å si hva som er den beste måten å legge opp treningen på for syklister. [@almquist2022] konkluderer med at deres data ikke støtter hypotesen om at BP er en bedre metode for trente syklister enn TD. Resultatene viser at det er litt forskjell på treningsutbyttet, men at den ikke er signifikant. Studien til [@javaloyes2020] skiller seg litt ut fra resten i og med at den har som mål å finne ut om HRV er et valid og reliabelt verktøy for å periodisere treningen. Derfor er det ikke fokus på hva som er mest effektivt av HRV og BP, men de konkluderer med at HRV er et godt hjelpemiddel og at man kan stole på det i trenignsplanleggingen.

## Avslutning

I denne oppgaven har jeg sett på frm forskjellige studier som handler om blokkperiodisering og VO<sub>2max</sub>. Jeg har forsåkt å analysere artiklene til disse studiene og se på hva slagt studiedesign de har brukt, hva slags statistiske metoder de har brukt og hva forskerne har funnet ut og konkludert med i studiene. Det siste punktet var litt vanskelig ettersom det bare var et av studiene jeg fant som forsket spesifikt på BP sin effekt på VO<sub>2max</sub>. Resten av studiene hadde mer generelt fokus på prestasjonsforbedring innenfor sykling hvor VO<sub>2max</sub> bare var en av mange variabler de forsket på. Jeg synes likevel det var spennende å se hvordan [@rønnestad2012a] og [@almquist2022] fikk forskjellige resultat. Disse studiene var veldig like, og Rønnestad var med i begge studiene, så det var interessant at resultatene ble såpass ulike. Alt i alt synes jeg alle artiklene var gode, og de virker svært seriøse, så det at resultatene ble ulike tyder bare på at det trengs mer forskning på feltet.
